### ISSUE TITLE
Sorting by playtime doesn't include sorting by custom overriden values

### ISSUE THREAD

**Issue by dustinvtran** [td-memo/memo#65]
Sorting by playtime shows entries sorted in ascending/descending order of their hours to finish. However, I think it only does so by the database value. It doesn't include the user-overwritten value. The entries below didn't have a database playtime value so I added my own; they aren't included in the sorting.

![2022-09-09 11_46_15](https://user-images.githubusercontent.com/2569867/189422253-8cbc440a-17c2-4fe6-9799-6789451e6d61.png)

**Comment by tam-carre** [comment]
c2dd506
