### ISSUE TITLE
Double log in text

### ISSUE THREAD

**Issue by dustinvtran** [td-memo/memo#66]
![2022-09-09 11_48_49](https://user-images.githubusercontent.com/2569867/189422706-473b18b1-d586-411e-8433-7ee52aadc6aa.png)

**Comment by tam-carre** [comment]
Is this systematic? Cannot reproduce

**Comment by dustinvtran** [comment]
I see it in an incognito Chrome window whenever going to nil.moe the frontpage. Also when logged out in a normal Chrome window and going to the frontpage.

Interestingly, I don't see it on Microsoft Edge though.

**Comment by tam-carre** [comment]
@dustinvtran Have you been experiencing this since we've changed authentication provider?

**Comment by dustinvtran** [comment]
Nope! I'll close.
