### ISSUE TITLE
can't search for title in books

### ISSUE THREAD

**Issue by dustinvtran** [td-memo/memo#70]
![2023-04-16 18_00_14](https://user-images.githubusercontent.com/2569867/232355022-8882a05c-66a3-477e-bdb8-9ce8c224187d.png)

**Comment by dustinvtran** [comment]
oh, it's happening for all databases.
![2023-04-16 19_08_33](https://user-images.githubusercontent.com/2569867/232361434-3337460e-1ea0-4b81-8739-907a42ed1a05.png)

**Comment by tam-carre** [comment]
okay i will check soon

**Comment by tam-carre** [comment]
should be fixed sorry for the delay

**Comment by dustinvtran** [comment]
thank you tam!
